import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/sonner"
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import Footer from "@/components/footer";
import { Navbar } from "@/components/shopLayout/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full` }
      >
        <SessionProvider>
         <div className="py-2 md:px-8 px-4 lg:px-16   w-full  h-full">
          <Navbar/>
          {children}
        </div>
          <Footer/>
        </SessionProvider>
        <Toaster />
      </body>
    </html>
  );
}

