import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/sonner"
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { Navbar } from "@/components/shopLayout/navbar";
import Footer from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased w-full` }
      >
         <div className="px-4 py-2 md:px-8 lg:px-16 w-full bg-main-500 h-full">
        <SessionProvider>
          <Navbar/>
          {children}
          <Footer/>
        </SessionProvider>
        </div>
        <Toaster />
      </body>
    </html>
  );
}

